[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dobishem"
authors = [{name = "John C. G. Sturdy", email = "jcg.sturdy@gmail.com"}]
description = "Python utilities for my other packages"
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]
version = "0.0.37"
dependencies = [
  "pyyaml"
]

[tool.pytest.ini_options]
pythonpath = [
  ".", "src",
]