[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dobishem"
authors = [{name = "John C. G. Sturdy", email = "jcg.sturdy@gmail.com"}]
description = "Python utilities for my other packages"
readme = "README.md"
license = "GPL-3.0-or-later"
version = "0.0.44"
dependencies = [
  "frozendict", "pyyaml"
]

[tool.pytest.ini_options]
pythonpath = [
  ".", "src",
]